spring:
  datasource:
    platform:
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        #TODO: Add PostgreSQL Schema
        default_schema:
        jdbc:
          lob:
            non_contextual_creation: true
