spring:
  datasource:
    platform:
    driverClassName: oracle.jdbc.OracleDriver
    url: ${alexa-order.datasource.url}
    user-name: ${alexa-order.datasource.user-name}
    password: ${alexa-order.datasource.password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
        #TODO: Add Schema
        default_schema:
