spring:
  application:
    name: alexa-order
  output:
    ansi:
      enabled: detect
  profiles:
    active: @spring.profiles.active@
  messages:
    basename: messages
    fallback-to-system-locale: true
  jmx:
    enabled: true

app:
  swagger:
    browsingBasePath: api/swagger
    enabled: true

springdoc:
  packagesToScan: com.advancestores.alexa.order
  pathsToMatch: /**
  swagger-ui:
    path: /swagger-ui.html

